-- lineage 메타데이터 스키마 (SQLite)
-- 외래키는 연결마다 PRAGMA foreign_keys = ON 을 실행해야 검사된다 (lineage/db.py 에서 처리)

CREATE TABLE IF NOT EXISTS OBJECT_INFO (
    OBJECT_ID     INTEGER  NOT NULL,
    OBJECT_NAME   TEXT     NOT NULL COLLATE NOCASE,          -- 대소문자 구분 없이 같은 객체로 취급
    OBJECT_TYPE   TEXT     NOT NULL,                         -- TABLE | VIEW
    SCHEMA_NAME   TEXT     NOT NULL DEFAULT '' COLLATE NOCASE, -- 스키마가 없으면 ''
    CREATED_DATE  DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (OBJECT_ID),
    UNIQUE (OBJECT_NAME, OBJECT_TYPE, SCHEMA_NAME)
);

CREATE TABLE IF NOT EXISTS OBJECT_RELATION (
    RELATION_ID       INTEGER  NOT NULL,
    SOURCE_OBJECT_ID  INTEGER  NOT NULL,
    TARGET_OBJECT_ID  INTEGER  NOT NULL,
    RELATION_TYPE     TEXT     NOT NULL DEFAULT 'LINEAGE',
    FILE_PATH         TEXT     NOT NULL DEFAULT '',          -- 관계를 만든 DDL 파일 (ddl 디렉터리 기준 상대경로)
    CREATED_DATE      DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RELATION_ID),
    -- 같은 A → B 관계를 여러 프로시저가 만들 수 있으므로 FILE_PATH 까지 포함
    UNIQUE (SOURCE_OBJECT_ID, TARGET_OBJECT_ID, RELATION_TYPE, FILE_PATH),
    CONSTRAINT "0" FOREIGN KEY (SOURCE_OBJECT_ID) REFERENCES OBJECT_INFO (OBJECT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "1" FOREIGN KEY (TARGET_OBJECT_ID) REFERENCES OBJECT_INFO (OBJECT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS IX_OBJECT_RELATION_TARGET ON OBJECT_RELATION (TARGET_OBJECT_ID);
